### ISSUE TITLE
Reproduce and share your model

### ISSUE THREAD

**Issue by whatrocks** [djbyrne/CNN-On-The-Cloud-#1]
Hey 👋 awesome use of the Floyd config file!

If you want to help others reproduce your work, you can add the **Run on FloydHub** button to your README. Here's a guide: https://docs.floydhub.com/guides/run_on_floydhub_button/

TL;DR - just add this to your readme file:

```
[![Run on FloydHub](https://static.floydhub.com/button/button.svg)](https://floydhub.com/run)
```

**Comment by djbyrne** [comment]
Hey whatrocks,

Thanks for the tip! I'll add that in now :)

**Comment by whatrocks** [comment]
Awesome!
